# Generated by Django 4.2.5 on 2023-09-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0002_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
