# Generated by Django 4.2.5 on 2023-09-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0004_workerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workerprofile',
        ),
    ]
