# Generated by Django 4.2.5 on 2023-09-15 14:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0005_delete_workerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(default=django.utils.timezone.now)),
                ('service_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_duration',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(default='Scheduled', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='technician_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiapp.worker'),
        ),
    ]
