# Generated by Django 4.2.5 on 2023-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0006_slot_appointment_appointment_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(default='20230915155346', max_length=20, unique=True),
        ),
    ]
