# Generated by Django 4.2.5 on 2023-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0007_appointment_appointment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='technician_assigned',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='service_date',
            field=models.DateField(),
        ),
    ]
