# Generated by Django 4.2.5 on 2023-09-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0010_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
