# Generated by Django 4.2.5 on 2023-09-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0011_worker_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiapp.appointment'),
        ),
    ]
