# Generated by Django 4.2.5 on 2023-09-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0015_audiorecording_user_audiorecording_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='audio_file',
            field=models.FileField(null=True, upload_to='audio_recordings/'),
        ),
    ]
