# Generated by Django 4.2.5 on 2023-09-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0017_leaverequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='service_date',
        ),
    ]
