# Generated by Django 4.2.5 on 2023-09-26 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0018_remove_slot_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='service_date',
            field=models.DateField(default=datetime.date(2023, 9, 26)),
        ),
    ]
