# Generated by Django 4.2.5 on 2023-09-26 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0019_slot_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
