# Generated by Django 4.2.5 on 2023-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0020_alter_slot_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='service_date',
            field=models.DateField(),
        ),
    ]
