# Generated by Django 4.2.5 on 2023-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0021_alter_slot_service_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='build_year',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='chassis_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='engine_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='registration_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vehicle_model',
            field=models.CharField(max_length=100),
        ),
    ]
