# Generated by Django 4.2.5 on 2023-09-27 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0022_remove_appointment_build_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
