# Generated by Django 4.2.5 on 2023-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0026_serviceprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTimePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_model', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('service_type', models.CharField(max_length=255)),
                ('service_history', models.IntegerField()),
                ('build_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('last_serviced_date', models.IntegerField()),
                ('current_year', models.IntegerField()),
                ('predicted_time', models.IntegerField()),
            ],
        ),
    ]
