# Generated by Django 4.2.5 on 2024-01-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0027_servicetimeprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
