# Generated by Django 4.2.5 on 2024-01-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0028_alter_task_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recognized_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
