# Generated by Django 4.2.5 on 2024-02-06 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0034_policyrecord_chassis_number_policyrecord_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=100)),
                ('incident_date', models.DateField()),
                ('description', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='accident_claims/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiapp.advisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
