# Generated by Django 4.2.5 on 2024-02-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0035_accidentclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentclaim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
