# Generated by Django 4.2.5 on 2024-02-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0036_accidentclaim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentclaim',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
