# Generated by Django 4.2.5 on 2024-02-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0037_accidentclaim_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentclaim',
            name='document',
        ),
        migrations.AddField(
            model_name='accidentclaim',
            name='dl_document',
            field=models.FileField(blank=True, null=True, upload_to='accident_claims/', verbose_name='Driving Licence Document'),
        ),
        migrations.AddField(
            model_name='accidentclaim',
            name='fir_document',
            field=models.FileField(blank=True, null=True, upload_to='accident_claims/', verbose_name='FIR Document'),
        ),
        migrations.AddField(
            model_name='accidentclaim',
            name='rc_document',
            field=models.FileField(blank=True, null=True, upload_to='accident_claims/', verbose_name='Registration Certificate Document'),
        ),
    ]
