# Generated by Django 4.2.5 on 2024-02-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0039_accidentclaim_assigned_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentclaim',
            name='assigned_worker',
        ),
    ]
