# Generated by Django 4.2.5 on 2024-02-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0041_alter_customuser_role_survivor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survivor',
            new_name='Surveyor',
        ),
    ]
