# Generated by Django 4.2.5 on 2024-02-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0042_rename_survivor_surveyor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Worker'), (2, 'Customer'), (3, 'Advisor'), (4, 'Surveyor')], null=True),
        ),
    ]
