# Generated by Django 4.2.5 on 2024-02-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0043_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
