# Generated by Django 4.2.5 on 2024-02-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0045_alter_accidentclaim_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentclaim',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='accidentclaim',
            name='assigned_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_advisor', to='vehiapp.advisor'),
        ),
        migrations.AddField(
            model_name='accidentclaim',
            name='assigned_surveyor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_surveyor', to='vehiapp.surveyor'),
        ),
    ]
