# Generated by Django 4.2.5 on 2024-03-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0047_policyrecord_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecord',
            name='idv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
