# Generated by Django 4.2.5 on 2024-03-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0048_policyrecord_idv'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecord',
            name='add_ons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='bike_make',
            field=models.CharField(default='****', max_length=255),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='bike_model',
            field=models.CharField(default='****', max_length=255),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='engine_capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='has_previous_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='owner_age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='owner_gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='riding_experience',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='voluntary_deductible',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
