# Generated by Django 4.2.5 on 2024-03-18 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0049_policyrecord_add_ons_policyrecord_bike_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentclaim',
            name='policy_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiapp.policyrecord'),
        ),
        migrations.AlterField(
            model_name='policyrecord',
            name='add_ons',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
