# Generated by Django 4.2.5 on 2024-03-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0051_roadsideassistancerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadsideassistancerequest',
            name='location',
        ),
        migrations.AddField(
            model_name='roadsideassistancerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='roadsideassistancerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20, null=True),
        ),
    ]
