# Generated by Django 4.2.5 on 2024-03-20 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0052_remove_roadsideassistancerequest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsideassistancerequest',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiapp.worker'),
        ),
    ]
