# Generated by Django 4.2.5 on 2024-03-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0053_roadsideassistancerequest_assigned_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsideassistancerequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
