# Generated by Django 4.2.5 on 2024-03-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0054_roadsideassistancerequest_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsideassistancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
