# Generated by Django 4.2.5 on 2024-03-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0055_roadsideassistancerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsideassistancerequest',
            name='otp',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='roadsideassistancerequest',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
